name: Run Raffle

on:
  workflow_dispatch:
    inputs:
      label:
        description: "Label used to filter the issues"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading raffle
        run: |
          curl -s https://api.github.com/repos/golangroma/raffle/releases/latest | \
            jq -r '.assets[] | select(.name|test("linux-x86_64")) | .browser_download_url' | \
            xargs wget -q -O raffle && \
            chmod +x raffle

      - name: Run
        run: ./raffle run --label "${{ github.event.inputs.label }}" ${GITHUB_REPOSITORY}
